---

- name: Create s3 bucket
  amazon.aws.s3_bucket:
    name: "{{ bucket_name }}"
    state: present

- name: Create policy file for bucket
  template:
    src: "{{ role_path }}/templates/s3-web-access-policy.json.j2"
    dest: "{{ role_path}}/files/s3-web-access-policy.json"

- name: Apply policy
  command: "aws s3api put-bucket-policy --bucket {{ bucket_name }} --policy file:///{{ role_path }}/files/s3-web-access-policy.json"

- name: upload blog to s3
  command: "aws s3 cp {{ blog_root_dir }}/ s3://{{ bucket_name }}/ --recursive"

- name: Add website configuration to the s3 bucket
  community.aws.s3_website:
    name: "{{ bucket_name }}"
    state: present
    suffix: index.html
    region: us-east-1
